#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEYS_DIR="$SCRIPT_DIR/keys"
KEY_PATH="$KEYS_DIR/docker-ssh-test"

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Function to generate SSH key if needed
setup_ssh_key() {
    # Create keys directory with proper permissions
    if [ ! -d "$KEYS_DIR" ]; then
        print_status "Creating SSH keys directory at $KEYS_DIR..." >&2
        mkdir -p "$KEYS_DIR"
        chmod 700 "$KEYS_DIR"
    fi
    
    if [ ! -f "$KEY_PATH" ]; then
        print_status "Generating SSH key pair for testing..." >&2
        ssh-keygen -t ed25519 -f "$KEY_PATH" -N "" -C "docker-ssh-test"
        
        # Set proper permissions on the keys
        chmod 600 "$KEY_PATH"
        chmod 644 "$KEY_PATH.pub"
        
        print_success "SSH key pair generated at $KEY_PATH" >&2
        print_status "Key permissions set: private key (600), public key (644)" >&2
    else
        print_warning "SSH key already exists at $KEY_PATH" >&2
        
        # Ensure permissions are correct even if key exists
        chmod 600 "$KEY_PATH"
        chmod 644 "$KEY_PATH.pub"
    fi
    
    # Return the public key content
    cat "$KEY_PATH.pub"
}

# Function to create .env.ssh file
create_env_file() {
    local public_key="$1"
    local env_file="$SCRIPT_DIR/.env.ssh"
    
    print_status "Creating .env.ssh file with your SSH public key..."
    
    # Write the environment file with the SSH public key
    {
        echo "# SSH Configuration for docker-ssh testing"
        echo "# This file is auto-generated by test-setup.sh"
        echo ""
        printf "AUTHORIZED_KEYS=%s\n" "$public_key"
    } > "$env_file"
    
    # Set permissions on env file
    chmod 600 "$env_file"
    print_success ".env.ssh file created with proper permissions (600)"
}

# Function to start services
start_services() {
    print_status "Starting test environment..."
    cd "$SCRIPT_DIR"
    docker compose -f docker-compose.test.yml up -d
    
    print_status "Waiting for services to be ready..."
    sleep 5
    
    # Check if services are running
    if docker compose -f docker-compose.test.yml ps | grep -q "Up"; then
        print_success "Test environment is running!"
    else
        print_error "Some services failed to start. Check logs with: docker compose -f docker-compose.test.yml logs"
        exit 1
    fi
}

# Function to run basic connectivity tests
run_basic_tests() {
    print_status "Running basic connectivity tests..."
    
    # Test SSH connection to unrestricted server
    if ssh -i "$KEY_PATH" -o ConnectTimeout=5 -o StrictHostKeyChecking=no tunnel@localhost -p 41222 "echo 'SSH connection test successful'" 2>/dev/null; then
        print_success "SSH connection to unrestricted server (port 41222) works"
    else
        print_error "SSH connection to unrestricted server failed"
    fi
    
    # Test SSH connection to restricted server
    if ssh -i "$KEY_PATH" -o ConnectTimeout=5 -o StrictHostKeyChecking=no tunnel@localhost -p 41223 "echo 'SSH connection test successful'" 2>/dev/null; then
        print_success "SSH connection to restricted server (port 41223) works"
    else
        print_error "SSH connection to restricted server failed"
    fi
    
    print_status "Basic tests completed. See TESTING.md for comprehensive testing instructions."
}

# Function to run comprehensive tunnel tests
run_other_tests() {
    print_status "Running comprehensive tunnel tests..."
    
    # Helper function to test tunnel
    test_tunnel() {
        local port="$1"
        local ssh_port="$2"
        local destination="$3"
        local description="$4"
        local expected_result="$5"  # "pass" or "fail"
        
        print_status "Testing: $description"
        
        # Start SSH tunnel in background
        ssh -i "$KEY_PATH" -o ConnectTimeout=5 -o StrictHostKeyChecking=no -L "$port:$destination" -N tunnel@localhost -p "$ssh_port" &
        local tunnel_pid=$!
        
        # Wait for tunnel to establish
        sleep 2
        
        # Test the tunnel
        local test_result="fail"
        if curl -s --connect-timeout 5 --max-time 10 "http://localhost:$port" >/dev/null 2>&1; then
            test_result="pass"
        fi
        
        # Kill the tunnel
        kill $tunnel_pid 2>/dev/null || true
        wait $tunnel_pid 2>/dev/null || true
        
        # Check if result matches expectation
        if [ "$test_result" = "$expected_result" ]; then
            print_success "$description - PASSED (expected: $expected_result, got: $test_result)"
        else
            print_error "$description - FAILED (expected: $expected_result, got: $test_result)"
        fi
    }
    
    # Test 1: Unrestricted tunneling (should work)
    test_tunnel "41089" "41222" "nginx:80" "Unrestricted tunneling to nginx" "pass"
    
    # Test 2: Restricted tunneling to allowed service (should work)
    test_tunnel "41088" "41223" "nginx:80" "Restricted tunneling to allowed service (nginx)" "pass"
    
    # Test 3: Restricted tunneling to blocked destination (should fail)
    test_tunnel "41087" "41223" "google.com:80" "Restricted tunneling to blocked destination (google.com)" "fail"
    
    # Test 4: No tunneling allowed (should fail)
    test_tunnel "41086" "41224" "nginx:80" "No tunneling allowed" "fail"
    
    print_status "Comprehensive tunnel tests completed."
}

# Function to show usage examples
show_examples() {
    echo
    print_status "Quick Test Examples:"
    echo
    echo "1. Test unrestricted tunneling (should work):"
    echo "   ssh -i $KEY_PATH -L 41089:nginx:80 -N tunnel@localhost -p 41222 & curl http://localhost:41089"
    echo
    echo "2. Test restricted tunneling to allowed service (should work):"
    echo "   ssh -i $KEY_PATH -L 41088:nginx:80 -N tunnel@localhost -p 41223 & curl http://localhost:41088"
    echo
    echo "3. Test restricted tunneling to blocked destination (should fail):"
    echo "   ssh -i $KEY_PATH -L 41087:google.com:80 -N tunnel@localhost -p 41223 & curl http://localhost:41087"
    echo
    echo "4. Test with no tunneling allowed (should fail):"
    echo "   ssh -i $KEY_PATH -L 41086:nginx:80 -N tunnel@localhost -p 41224 & curl http://localhost:41086"
    echo
    print_status "For detailed testing instructions, see TESTING.md"
}

# Function to clean up
cleanup() {
    print_status "Cleaning up test environment..."
    cd "$SCRIPT_DIR"
    
    # Stop and remove containers, networks, and volumes
    docker compose -f docker-compose.test.yml down --volumes
    
    # Remove built images
    print_status "Removing test Docker images..."
    docker compose -f docker-compose.test.yml down --rmi all 2>/dev/null || true
    
    # Clean up SSH known_hosts entries for test ports
    print_status "Cleaning up SSH known_hosts entries..."
    ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:41222" 2>/dev/null || true
    ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:41223" 2>/dev/null || true
    ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:41224" 2>/dev/null || true
    ssh-keygen -f "$HOME/.ssh/known_hosts" -R "[localhost]:41225" 2>/dev/null || true
    
    # Kill any lingering SSH tunnels
    pkill -f "ssh.*-L.*localhost" 2>/dev/null || true
    
    print_success "Cleanup completed"
}

# Function to show key information
show_key_info() {
    if [ -f "$KEY_PATH" ]; then
        echo
        print_status "SSH Key Information:"
        echo "   Private key: $KEY_PATH"
        echo "   Public key:  $KEY_PATH.pub"
        echo "   Permissions: $(ls -la "$KEY_PATH" | awk '{print $1 " " $3 ":" $4}')"
        echo "   Permissions: $(ls -la "$KEY_PATH.pub" | awk '{print $1 " " $3 ":" $4}')"
        echo
        print_status "Public key content:"
        cat "$KEY_PATH.pub"
    else
        print_warning "No SSH key found at $KEY_PATH"
    fi
}

# Main script
main() {
    echo "🐳 Docker SSH ALLOWED_DEST Test Setup"
    echo "====================================="
    echo
    
    # Check prerequisites
    if ! command_exists docker; then
        print_error "Docker is not installed or not in PATH"
        exit 1
    fi
    
    if ! docker compose version >/dev/null 2>&1; then
        print_error "Docker Compose is not installed or not in PATH"
        exit 1
    fi
    
    # Parse command line arguments
    case "${1:-setup}" in
        "setup")
            print_status "Setting up test environment..."
            public_key=$(setup_ssh_key)
            create_env_file "$public_key"
            start_services
            run_basic_tests
            run_other_tests
            show_examples
            ;;
        "start")
            start_services
            ;;
        "test")
            run_basic_tests
            ;;
        "test-all")
            run_basic_tests
            run_other_tests
            ;;
        "examples")
            show_examples
            ;;
        "cleanup")
            cleanup
            ;;
        "key-info")
            show_key_info
            ;;
        "help"|"-h"|"--help")
            echo "Usage: $0 [command]"
            echo
            echo "Commands:"
            echo "  setup     (default) Complete setup: generate SSH key, create env file, start services"
            echo "  start     Start the Docker Compose services"
            echo "  test      Run basic connectivity tests"
            echo "  test-all  Run basic tests and comprehensive tunnel tests"
            echo "  examples  Show testing examples"
            echo "  key-info  Show SSH key information and location"
            echo "  cleanup   Stop services and clean up"
            echo "  help      Show this help message"
            echo
            echo "SSH keys are stored in: $KEYS_DIR"
            echo "Environment file: $SCRIPT_DIR/.env.ssh"
            ;;
        *)
            print_error "Unknown command: $1"
            print_status "Use '$0 help' for usage information"
            exit 1
            ;;
    esac
}

# Run main function with all arguments
main "$@"